name: grocery_flutter
description: Bachat Gat (Self Help Group) Android Financial Management Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  url_launcher: ^6.3.2
  intl: ^0.17.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
