import '../models/member.dart';
import '../repositories/group_repository.dart';

class DataImportService {
  static const String groupId = 'shivshahi_group_001';
  static const double defaultPerShareHafta = 1000.0;

  /// Master member data extracted from the supplied register screenshots.
  ///
  /// Rules:
  /// - Final seeded member count = 363.
  /// - Blank register rows 364, 365 and 366 are ignored.
  /// - Where a multi-share entry was collapsed in the register, it is expanded
  ///   into separate numbered member records (Name 1, Name 2, ...).
  /// - Every seeded record represents exactly 1 share.
  /// - Default monthly hafta per seeded share = ₹1,000.
  /// - Phone number is intentionally empty.
  static final List<Map<String, dynamic>> masterDataset = [
    {'srNo': 1, 'name': 'अनिल सखाराम गाडेकर', 'shares': 1},
    {'srNo': 2, 'name': 'सार्थक अनिल गाडेकर', 'shares': 1},
    {'srNo': 3, 'name': 'सविता अनिल गाडेकर', 'shares': 1},
    {'srNo': 4, 'name': 'किशोर गणपत गाडेकर', 'shares': 1},
    {'srNo': 5, 'name': 'चेतन दत्तात्रय गाडेकर', 'shares': 1},
    {'srNo': 6, 'name': 'साईराज दत्तात्रय गाडेकर', 'shares': 1},
    {'srNo': 7, 'name': 'प्रसाद अशोक गाडेकर', 'shares': 1},
    {'srNo': 8, 'name': 'मनिषा अशोक गाडेकर', 'shares': 1},
    {'srNo': 9, 'name': 'गौरी तुषार घोलप', 'shares': 1},
    {'srNo': 10, 'name': 'राहुल ज्ञानेश्वर गाडेकर', 'shares': 1},
    {'srNo': 11, 'name': 'अनिकेत संजय गाडेकर', 'shares': 1},
    {'srNo': 12, 'name': 'दिनकर रामभाऊ गाडेकर', 'shares': 1},
    {'srNo': 13, 'name': 'सौरभ दिनकर गाडेकर', 'shares': 1},
    {'srNo': 14, 'name': 'संतोष दत्तात्रय गाडेकर', 'shares': 1},
    {'srNo': 15, 'name': 'कार्तिक संतोष गाडेकर', 'shares': 1},
    {'srNo': 16, 'name': 'भाऊसाहेब निवृत्ती गाडेकर 1', 'shares': 1},
    {'srNo': 17, 'name': 'भाऊसाहेब निवृत्ती गाडेकर 2', 'shares': 1},
    {'srNo': 18, 'name': 'भाऊसाहेब निवृत्ती गाडेकर 3', 'shares': 1},
    {'srNo': 19, 'name': 'भाऊसाहेब निवृत्ती गाडेकर 4', 'shares': 1},
    {'srNo': 20, 'name': 'भाऊसाहेब निवृत्ती गाडेकर 5', 'shares': 1},
    {'srNo': 21, 'name': 'गणेश सुभाष गाडेकर', 'shares': 1},
    {'srNo': 22, 'name': 'स्वप्निल भरत मंडलक', 'shares': 1},
    {'srNo': 23, 'name': 'भगवंता सुभाष गाडेकर', 'shares': 1},
    {'srNo': 24, 'name': 'अनिल जयराम गाडेकर', 'shares': 1},
    {'srNo': 25, 'name': 'विकास जयराम गाडेकर', 'shares': 1},
    {'srNo': 26, 'name': 'ओमकार अनिल गाडेकर', 'shares': 1},
    {'srNo': 27, 'name': 'राजेंद्र सिताराम गाडेकर', 'shares': 1},
    {'srNo': 28, 'name': 'देविदास दगडू गाडेकर', 'shares': 1},
    {'srNo': 29, 'name': 'प्रणव देविदास गाडेकर', 'shares': 1},
    {'srNo': 30, 'name': 'तुषार गणपत गाडेकर', 'shares': 1},
    {'srNo': 31, 'name': 'प्रणाली तुषार गाडेकर', 'shares': 1},
    {'srNo': 32, 'name': 'गणपत ठका गाडेकर', 'shares': 1},
    {'srNo': 33, 'name': 'प्रतिभा भिमाशंकर कोठवळ', 'shares': 1},
    {'srNo': 34, 'name': 'रोहिणी भिमाशंकर कोठवळ', 'shares': 1},
    {'srNo': 35, 'name': 'सार्थक सोपान गाडेकर', 'shares': 1},
    {'srNo': 36, 'name': 'सोपान तुकाराम गाडेकर', 'shares': 1},
    {'srNo': 37, 'name': 'विजय तुकाराम गाडेकर', 'shares': 1},
    {'srNo': 38, 'name': 'संकेत बाळासाहेब गाडेकर', 'shares': 1},
    {'srNo': 39, 'name': 'ज्ञानेश्वरी विजय गाडेकर', 'shares': 1},
    {'srNo': 40, 'name': 'माऊली सोपान गाडेकर', 'shares': 1},
    {'srNo': 41, 'name': 'विनायक नामदेव गाडेकर', 'shares': 1},
    {'srNo': 42, 'name': 'संदिप गुलाबचंद लोढा', 'shares': 1},
    {'srNo': 43, 'name': 'तुषार रसिक लोढा', 'shares': 1},
    {'srNo': 44, 'name': 'वरद विनायक गाडेकर', 'shares': 1},
    {'srNo': 45, 'name': 'कार्तिकी विजय गाडेकर', 'shares': 1},
    {'srNo': 46, 'name': 'नितीन वसंत गाडेकर', 'shares': 1},
    {'srNo': 47, 'name': 'सोपान पंढरीनाथ गाडेकर', 'shares': 1},
    {'srNo': 48, 'name': 'ज्ञानेश्वर भाऊसाहेब गाडेकर', 'shares': 1},
    {'srNo': 49, 'name': 'सागर बाळासाहेब गाडेकर', 'shares': 1},
    {'srNo': 50, 'name': 'जिवन बाळासाहेब गाडेकर', 'shares': 1},
    {'srNo': 51, 'name': 'गणेश दत्तात्रय गाडेकर', 'shares': 1},
    {'srNo': 52, 'name': 'धनंजय दत्तात्रय गाडेकर', 'shares': 1},
    {'srNo': 53, 'name': 'अक्षय संपत गाडेकर', 'shares': 1},
    {'srNo': 54, 'name': 'सागर संपत गाडेकर', 'shares': 1},
    {'srNo': 55, 'name': 'अंकुश दगडू गाडेकर', 'shares': 1},
    {'srNo': 56, 'name': 'प्रमोद चंद्रकांत बेळे', 'shares': 1},
    {'srNo': 57, 'name': 'संदिप लक्ष्मण साबळे', 'shares': 1},
    {'srNo': 58, 'name': 'दत्ता बबन वाकळे', 'shares': 1},
    {'srNo': 59, 'name': 'भाग्यश्री दत्ता वाकळे', 'shares': 1},
    {'srNo': 60, 'name': 'आर्या दत्ता वाकळे', 'shares': 1},
    {'srNo': 61, 'name': 'स्वरा दत्ता वाकळे', 'shares': 1},
    {'srNo': 62, 'name': 'ओंकार आण्णासाहेब वाकळे', 'shares': 1},
    {'srNo': 63, 'name': 'दत्तात्रय मुरलीधर सुपेकर', 'shares': 1},
    {'srNo': 64, 'name': 'अखिलेष दावल सुपेकर', 'shares': 1},
    {'srNo': 65, 'name': 'निलेश गेणूजी सुपेकर', 'shares': 1},
    {'srNo': 66, 'name': 'श्रेयश दत्तात्रय सुपेकर', 'shares': 1},
    {'srNo': 67, 'name': 'मदन सिताराम भागवत', 'shares': 1},
    {'srNo': 68, 'name': 'साईराज मदन भागवत', 'shares': 1},
    {'srNo': 69, 'name': 'धर्मा पंडित जगताप', 'shares': 1},
    {'srNo': 70, 'name': 'रोहित धर्मा जगताप', 'shares': 1},
    {'srNo': 71, 'name': 'निशांत बाळाजी वाळुंज', 'shares': 1},
    {'srNo': 72, 'name': 'शिवम कैलास कोल्हाळ', 'shares': 1},
    {'srNo': 73, 'name': 'नवनाथ लक्ष्मण खंडागळे', 'shares': 1},
    {'srNo': 74, 'name': 'अविनाश लक्ष्मण खंडागळे', 'shares': 1},
    {'srNo': 75, 'name': 'धनंजय कैलास सातपुते', 'shares': 1},
    {'srNo': 76, 'name': 'कैलास जगन्नाथ सातपुते', 'shares': 1},
    {'srNo': 77, 'name': 'बब्लू कैलास सातपुते 1', 'shares': 1},
    {'srNo': 78, 'name': 'बब्लू कैलास सातपुते 2', 'shares': 1},
    {'srNo': 79, 'name': 'गणेश महादु भोर', 'shares': 1},
    {'srNo': 80, 'name': 'राहुल विलास हांडे', 'shares': 1},
    {'srNo': 81, 'name': 'बाळासाहेब बन्सी कान्होरे', 'shares': 1},
    {'srNo': 82, 'name': 'सागर हिरालाल चोपडा', 'shares': 1},
    {'srNo': 83, 'name': 'वैभव हिरालाल चोपडा', 'shares': 1},
    {'srNo': 84, 'name': 'रेखा हिरालाल चोपडा', 'shares': 1},
    {'srNo': 85, 'name': 'रक्षित सागर चोपडा', 'shares': 1},
    {'srNo': 86, 'name': 'रफिक इब्राहिम पठाण', 'shares': 1},
    {'srNo': 87, 'name': 'किशोर सुखदेव जाधव', 'shares': 1},
    {'srNo': 88, 'name': 'रविंद्र सुखदेव जाधव', 'shares': 1},
    {'srNo': 89, 'name': 'गणेश शंकर जाधव', 'shares': 1},
    {'srNo': 90, 'name': 'विठ्ठल बाळासाहेब जाधव', 'shares': 1},
    {'srNo': 91, 'name': 'रविराज शंकर जाधव', 'shares': 1},
    {'srNo': 92, 'name': 'किशोर गंगाराम रोडे', 'shares': 1},
    {'srNo': 93, 'name': 'राम उद्गार सिंह', 'shares': 1},
    {'srNo': 94, 'name': 'मंथन सुनिल डोके', 'shares': 1},
    {'srNo': 95, 'name': 'अर्चना सुनिल डोके', 'shares': 1},
    {'srNo': 96, 'name': 'समर्थ संदिप डोके', 'shares': 1},
    {'srNo': 97, 'name': 'संदिप भाऊसाहेब डोके', 'shares': 1},
    {'srNo': 98, 'name': 'जावेद इस्माईल शेख', 'shares': 1},
    {'srNo': 99, 'name': 'रसिक फकिरमहंमद शेख', 'shares': 1},
    {'srNo': 100, 'name': 'आरिफा रसिक शेख', 'shares': 1},
    {'srNo': 101, 'name': 'परविन रसिक शेख', 'shares': 1},
    {'srNo': 102, 'name': 'रियाज जासुद्दीन शेख', 'shares': 1},
    {'srNo': 103, 'name': 'हसन इस्माईल सय्यद', 'shares': 1},
    {'srNo': 104, 'name': 'मोहंमद हसन सय्यद', 'shares': 1},
    {'srNo': 105, 'name': 'दिलावर रज्जाक सय्यद', 'shares': 1},
    {'srNo': 106, 'name': 'रज्जाक इस्माईल सय्यद', 'shares': 1},
    {'srNo': 107, 'name': 'मुश्ताक सलीम शेख', 'shares': 1},
    {'srNo': 108, 'name': 'सलीम बाबुभाई शेख', 'shares': 1},
    {'srNo': 109, 'name': 'आरिश रियाज जमादार', 'shares': 1},
    {'srNo': 110, 'name': 'मुसाभाई बाबु शेख', 'shares': 1},
    {'srNo': 111, 'name': 'अनिल लक्ष्मण शिरोळे', 'shares': 1},
    {'srNo': 112, 'name': 'राजु मगन नरवडे', 'shares': 1},
    {'srNo': 113, 'name': 'साई राजु नरवडे', 'shares': 1},
    {'srNo': 114, 'name': 'दत्तात्रय जगन्नाथ वाकचौरे', 'shares': 1},
    {'srNo': 115, 'name': 'अक्षय दत्तात्रय वाकचौरे 1', 'shares': 1},
    {'srNo': 116, 'name': 'अक्षय दत्तात्रय वाकचौरे 2', 'shares': 1},
    {'srNo': 117, 'name': 'सायली स्वप्निल खोल्लुम 1', 'shares': 1},
    {'srNo': 118, 'name': 'सायली स्वप्निल खोल्लुम 2', 'shares': 1},
    {'srNo': 119, 'name': 'सायली स्वप्निल खोल्लुम 3', 'shares': 1},
    {'srNo': 120, 'name': 'सायली स्वप्निल खोल्लुम 4', 'shares': 1},
    {'srNo': 121, 'name': 'सायली स्वप्निल खोल्लुम 5', 'shares': 1},
    {'srNo': 122, 'name': 'अमोल सुभाष खोल्लुम', 'shares': 1},
    {'srNo': 123, 'name': 'अन्वित अमोल खोल्लुम', 'shares': 1},
    {'srNo': 124, 'name': 'पल्लवी तुषार लोढा', 'shares': 1},
    {'srNo': 125, 'name': 'सचिन प्रभाकर पांडे', 'shares': 1},
    {'srNo': 126, 'name': 'तुषार प्रभाकर पांडे', 'shares': 1},
    {'srNo': 127, 'name': 'मयुरशेठ गडगे', 'shares': 1},
    {'srNo': 128, 'name': 'अविनाश सुभाष खोल्लुम', 'shares': 1},
    {'srNo': 129, 'name': 'सिद्धु शामराव आहेर', 'shares': 1},
    {'srNo': 130, 'name': 'सुदाम नामदेव शिंगोटे', 'shares': 1},
    {'srNo': 131, 'name': 'आकाश सुदाम शिंगोटे', 'shares': 1},
    {'srNo': 132, 'name': 'अरुण दशरथ भालेकर', 'shares': 1},
    {'srNo': 133, 'name': 'डॉ. दत्तात्रय कोंडाजी हांडे', 'shares': 1},
    {'srNo': 134, 'name': 'डॉ. अभिषेक दत्तात्रय हांडे', 'shares': 1},
    {'srNo': 135, 'name': 'अजिंक्य श्रीकांत घाटकर', 'shares': 1},
    {'srNo': 136, 'name': 'स्मिता श्रीकांत घाटकर', 'shares': 1},
    {'srNo': 137, 'name': 'अजिंक्य गोकुळ कहाणे', 'shares': 1},
    {'srNo': 138, 'name': 'निकीता अजिंक्य कहाणे', 'shares': 1},
    {'srNo': 139, 'name': 'शिवाय अजिंक्य कहाणे', 'shares': 1},
    {'srNo': 140, 'name': 'गोरक्ष दशरथ पिसाळ', 'shares': 1},
    {'srNo': 141, 'name': 'वेणूबाई दशरथ पिसाळ', 'shares': 1},
    {'srNo': 142, 'name': 'कार्तिकी गोरख पिसाळ', 'shares': 1},
    {'srNo': 143, 'name': 'आराध्य गोरख पिसाळ', 'shares': 1},
    {'srNo': 144, 'name': 'राहुल कचरदास पिसाळ', 'shares': 1},
    {'srNo': 145, 'name': 'दत्तात्रय बबन डोंगरे', 'shares': 1},
    {'srNo': 146, 'name': 'महेश सुरेश घाटकर', 'shares': 1},
    {'srNo': 147, 'name': 'डॉ. प्रतिक अरुण भालेराव', 'shares': 1},
    {'srNo': 148, 'name': 'आदेश उद्धव गणपुले', 'shares': 1},
    {'srNo': 149, 'name': 'ऋषिकेश उद्धव गणपुले', 'shares': 1},
    {'srNo': 150, 'name': 'राहुल अशोक आहेर', 'shares': 1},
    {'srNo': 151, 'name': 'आरव राहुल आहेर 1', 'shares': 1},
    {'srNo': 152, 'name': 'तुषार बाबाजी भोर', 'shares': 1},
    {'srNo': 153, 'name': 'शौर्य तुषार भोर', 'shares': 1},
    {'srNo': 154, 'name': 'वर्धन तुषार भोर', 'shares': 1},
    {'srNo': 155, 'name': 'अमित रामचंद्र गुंजाळ', 'shares': 1},
    {'srNo': 156, 'name': 'रामचंद्र कोंडीबा गुंजाळ', 'shares': 1},
    {'srNo': 157, 'name': 'प्रसाद सुभाष मिसाळ', 'shares': 1},
    {'srNo': 158, 'name': 'दत्तात्रय राजाराम खंडागळे', 'shares': 1},
    {'srNo': 159, 'name': 'विराज विकास कोरडे', 'shares': 1},
    {'srNo': 160, 'name': 'विकास नानाभाऊ कोरडे', 'shares': 1},
    {'srNo': 161, 'name': 'देवयानी विकास कोरडे', 'shares': 1},
    {'srNo': 162, 'name': 'सुभाष शिवाजी मिसाळ', 'shares': 1},
    {'srNo': 163, 'name': 'श्रीनिवास ज्ञानदेव कोकाटे', 'shares': 1},
    {'srNo': 164, 'name': 'जयसिंग धोंडीभाऊ नाईकवाडी', 'shares': 1},
    {'srNo': 165, 'name': 'छाया जयसिंग नाईकवाडी', 'shares': 1},
    {'srNo': 166, 'name': 'स्वप्निल जयसिंग नाईकवाडी', 'shares': 1},
    {'srNo': 167, 'name': 'समिर जयसिंग नाईकवाडी', 'shares': 1},
    {'srNo': 168, 'name': 'अन्वीर स्वप्निल नाईकवाडी', 'shares': 1},
    {'srNo': 169, 'name': 'ज्योती संतोष नाईकवाडी', 'shares': 1},
    {'srNo': 170, 'name': 'संजय दादाभाऊ मधे', 'shares': 1},
    {'srNo': 171, 'name': 'विजय भाऊसाहेब धात्रक', 'shares': 1},
    {'srNo': 172, 'name': 'देवांश विजय धात्रक', 'shares': 1},
    {'srNo': 173, 'name': 'राजेंद्र सुदाम धात्रक', 'shares': 1},
    {'srNo': 174, 'name': 'गणपत लक्ष्मण शेंगाळ', 'shares': 1},
    {'srNo': 175, 'name': 'नारायण गणपत शेंगाळ', 'shares': 1},
    {'srNo': 176, 'name': 'संतोष किसन घोडे', 'shares': 1},
    {'srNo': 177, 'name': 'सोनाली संतोष घोडे', 'shares': 1},
    {'srNo': 178, 'name': 'देवांशी संतोष घोडे', 'shares': 1},
    {'srNo': 179, 'name': 'अक्षय थोरात 1', 'shares': 1},
    {'srNo': 180, 'name': 'अक्षय थोरात 2', 'shares': 1},
    {'srNo': 181, 'name': 'अक्षय थोरात 3', 'shares': 1},
    {'srNo': 182, 'name': 'अक्षय थोरात 4', 'shares': 1},
    {'srNo': 183, 'name': 'अनिल दत्तात्रय नाईकवाडी', 'shares': 1},
    {'srNo': 184, 'name': 'राहुल शंकर घोलप', 'shares': 1},
    {'srNo': 185, 'name': 'शंकर नारायण घोलप', 'shares': 1},
    {'srNo': 186, 'name': 'देविदास शांताराम घोलप', 'shares': 1},
    {'srNo': 187, 'name': 'संजय मधुकर दिघे', 'shares': 1},
    {'srNo': 188, 'name': 'बाळासाहेब महादेव मते', 'shares': 1},
    {'srNo': 189, 'name': 'विनोद गुंजाळ 1', 'shares': 1},
    {'srNo': 190, 'name': 'विनोद गुंजाळ 2', 'shares': 1},
    {'srNo': 191, 'name': 'विनोद गुंजाळ 3', 'shares': 1},
    {'srNo': 192, 'name': 'विनोद गुंजाळ 4', 'shares': 1},
    {'srNo': 193, 'name': 'सुनिता प्रणेश शिंगोटे', 'shares': 1},
    {'srNo': 194, 'name': 'अलका सुनिल नलावडे', 'shares': 1},
    {'srNo': 195, 'name': 'सुनिल सोनबा नलावडे', 'shares': 1},
    {'srNo': 196, 'name': 'निधी सुनिल नलावडे', 'shares': 1},
    {'srNo': 197, 'name': 'निलेश रामदास आहेर', 'shares': 1},
    {'srNo': 198, 'name': 'समिर रामदास आहेर', 'shares': 1},
    {'srNo': 199, 'name': 'मच्छिंद्र शंकर आहेर (पप्पु)', 'shares': 1},
    {'srNo': 200, 'name': 'संतोष सोमनाथ आहेर', 'shares': 1},
    {'srNo': 201, 'name': 'सविता संतोष आहेर', 'shares': 1},
    {'srNo': 202, 'name': 'राजेंद्र सुभाष आहेर 1', 'shares': 1},
    {'srNo': 203, 'name': 'सई राजेंद्र आहेर', 'shares': 1},
    {'srNo': 204, 'name': 'सुभाष मल्हारी आहेर', 'shares': 1},
    {'srNo': 205, 'name': 'मच्छिंद्र सुभाष आहेर', 'shares': 1},
    {'srNo': 206, 'name': 'राजेंद्र सुभाष आहेर 2', 'shares': 1},
    {'srNo': 207, 'name': 'महेश मनोहर आहेर 1', 'shares': 1},
    {'srNo': 208, 'name': 'महेश मनोहर आहेर 2', 'shares': 1},
    {'srNo': 209, 'name': 'महेश मनोहर आहेर 3', 'shares': 1},
    {'srNo': 210, 'name': 'महेश मनोहर आहेर 4', 'shares': 1},
    {'srNo': 211, 'name': 'महेश मनोहर आहेर 5', 'shares': 1},
    {'srNo': 212, 'name': 'निलेश मारुती आहेर', 'shares': 1},
    {'srNo': 213, 'name': 'सुवर्णा निलेश आहेर', 'shares': 1},
    {'srNo': 214, 'name': 'रमेश लक्ष्मण आहेर', 'shares': 1},
    {'srNo': 215, 'name': 'अरुण भागुजी आहेर', 'shares': 1},
    {'srNo': 216, 'name': 'सतिष भागुजी आहेर', 'shares': 1},
    {'srNo': 217, 'name': 'आराध्या सतिष आहेर', 'shares': 1},
    {'srNo': 218, 'name': 'महेंद्र सुदाम आहेर', 'shares': 1},
    {'srNo': 219, 'name': 'ललिता महेंद्र आहेर', 'shares': 1},
    {'srNo': 220, 'name': 'विकास रमेश आहेर', 'shares': 1},
    {'srNo': 221, 'name': 'सोहम विकास आहेर', 'shares': 1},
    {'srNo': 222, 'name': 'श्रेयश विकास आहेर', 'shares': 1},
    {'srNo': 223, 'name': 'सचिन सुदाम आहेर', 'shares': 1},
    {'srNo': 224, 'name': 'किरण कोंडाजी गागरे', 'shares': 1},
    {'srNo': 225, 'name': 'माया किरण गागरे', 'shares': 1},
    {'srNo': 226, 'name': 'शिवतेज किरण गागरे', 'shares': 1},
    {'srNo': 227, 'name': 'शिवकन्या किरण गागरे', 'shares': 1},
    {'srNo': 228, 'name': 'शिवकलेक्शन गागरे', 'shares': 1},
    {'srNo': 229, 'name': 'निलेश अशोक आहेर', 'shares': 1},
    {'srNo': 230, 'name': 'योगेश अशोक आहेर', 'shares': 1},
    {'srNo': 231, 'name': 'कल्पेश कमलाकर आहेर', 'shares': 1},
    {'srNo': 232, 'name': 'सई कल्पेश आहेर', 'shares': 1},
    {'srNo': 233, 'name': 'दत्तात्रय महादु आहेर', 'shares': 1},
    {'srNo': 234, 'name': 'विजया दत्तात्रय आहेर', 'shares': 1},
    {'srNo': 235, 'name': 'संकेत दत्तात्रय आहेर', 'shares': 1},
    {'srNo': 236, 'name': 'शितल दत्तात्रय आहेर', 'shares': 1},
    {'srNo': 237, 'name': 'कस्तुरी सुनिल सोनवणे', 'shares': 1},
    {'srNo': 238, 'name': 'कार्तिकी सुनिल सोनवणे', 'shares': 1},
    {'srNo': 239, 'name': 'आरव राहुल आहेर 2', 'shares': 1},
    {'srNo': 240, 'name': 'रोहित सुभाष आहेर', 'shares': 1},
    {'srNo': 241, 'name': 'हितेश रोहित आहेर', 'shares': 1},
    {'srNo': 242, 'name': 'हरिदास यादवराव आहेर 1', 'shares': 1},
    {'srNo': 243, 'name': 'हरिदास यादवराव आहेर 2', 'shares': 1},
    {'srNo': 244, 'name': 'हरिदास यादवराव आहेर 3', 'shares': 1},
    {'srNo': 245, 'name': 'हरिदास यादवराव आहेर 4', 'shares': 1},
    {'srNo': 246, 'name': 'हरिदास यादवराव आहेर 5', 'shares': 1},
    {'srNo': 247, 'name': 'सविता सचिन शिंदे', 'shares': 1},
    {'srNo': 248, 'name': 'संकल्प सचिन शिंदे', 'shares': 1},
    {'srNo': 249, 'name': 'सोपान पाटे', 'shares': 1},
    {'srNo': 250, 'name': 'सिद्धेश सोपान पाटे', 'shares': 1},
    {'srNo': 251, 'name': 'कोमल सोपान पाटे', 'shares': 1},
    {'srNo': 252, 'name': 'सिद्धी सोपान पाटे', 'shares': 1},
    {'srNo': 253, 'name': 'आदेश सखाराम पुंड', 'shares': 1},
    {'srNo': 254, 'name': 'वनिता सखाराम पुंड', 'shares': 1},
    {'srNo': 255, 'name': 'शैलेश पोखरकर 1', 'shares': 1},
    {'srNo': 256, 'name': 'शैलेश पोखरकर 2', 'shares': 1},
    {'srNo': 257, 'name': 'शैलेश पोखरकर 3', 'shares': 1},
    {'srNo': 258, 'name': 'शैलेश पोखरकर 4', 'shares': 1},
    {'srNo': 259, 'name': 'शैलेश पोखरकर 5', 'shares': 1},
    {'srNo': 260, 'name': 'शैलेश पोखरकर 6', 'shares': 1},
    {'srNo': 261, 'name': 'वेदांत चेतन कहाणे', 'shares': 1},
    {'srNo': 262, 'name': 'संभाजी तान्हाजी आहेर 1', 'shares': 1},
    {'srNo': 263, 'name': 'संभाजी तान्हाजी आहेर 2', 'shares': 1},
    {'srNo': 264, 'name': 'संभाजी तान्हाजी आहेर 3', 'shares': 1},
    {'srNo': 265, 'name': 'संभाजी तान्हाजी आहेर 4', 'shares': 1},
    {'srNo': 266, 'name': 'संभाजी तान्हाजी आहेर 5', 'shares': 1},
    {'srNo': 267, 'name': 'संभाजी तान्हाजी आहेर 6', 'shares': 1},
    {'srNo': 268, 'name': 'संभाजी तान्हाजी आहेर 7', 'shares': 1},
    {'srNo': 269, 'name': 'संभाजी तान्हाजी आहेर 8', 'shares': 1},
    {'srNo': 270, 'name': 'संभाजी तान्हाजी आहेर 9', 'shares': 1},
    {'srNo': 271, 'name': 'संभाजी तान्हाजी आहेर 10', 'shares': 1},
    {'srNo': 272, 'name': 'संभाजी तान्हाजी आहेर 11', 'shares': 1},
    {'srNo': 273, 'name': 'संभाजी तान्हाजी आहेर 12', 'shares': 1},
    {'srNo': 274, 'name': 'संभाजी तान्हाजी आहेर 13', 'shares': 1},
    {'srNo': 275, 'name': 'संभाजी तान्हाजी आहेर 14', 'shares': 1},
    {'srNo': 276, 'name': 'संभाजी तान्हाजी आहेर 15', 'shares': 1},
    {'srNo': 277, 'name': 'संभाजी तान्हाजी आहेर 16', 'shares': 1},
    {'srNo': 278, 'name': 'संभाजी तान्हाजी आहेर 17', 'shares': 1},
    {'srNo': 279, 'name': 'संभाजी तान्हाजी आहेर 18', 'shares': 1},
    {'srNo': 280, 'name': 'संभाजी तान्हाजी आहेर 19', 'shares': 1},
    {'srNo': 281, 'name': 'संभाजी तान्हाजी आहेर 20', 'shares': 1},
    {'srNo': 282, 'name': 'बाजीराव देवराम कुरकुटे 1', 'shares': 1},
    {'srNo': 283, 'name': 'बाजीराव देवराम कुरकुटे 2', 'shares': 1},
    {'srNo': 284, 'name': 'बाजीराव देवराम कुरकुटे 3', 'shares': 1},
    {'srNo': 285, 'name': 'बाजीराव देवराम कुरकुटे 4', 'shares': 1},
    {'srNo': 286, 'name': 'बाजीराव देवराम कुरकुटे 5', 'shares': 1},
    {'srNo': 287, 'name': 'बाजीराव देवराम कुरकुटे 6', 'shares': 1},
    {'srNo': 288, 'name': 'बाजीराव देवराम कुरकुटे 7', 'shares': 1},
    {'srNo': 289, 'name': 'बाजीराव देवराम कुरकुटे 8', 'shares': 1},
    {'srNo': 290, 'name': 'बाजीराव देवराम कुरकुटे 9', 'shares': 1},
    {'srNo': 291, 'name': 'बाजीराव देवराम कुरकुटे 10', 'shares': 1},
    {'srNo': 292, 'name': 'बाजीराव देवराम कुरकुटे 11', 'shares': 1},
    {'srNo': 293, 'name': 'बाजीराव देवराम कुरकुटे 12', 'shares': 1},
    {'srNo': 294, 'name': 'बाजीराव देवराम कुरकुटे 13', 'shares': 1},
    {'srNo': 295, 'name': 'बाजीराव देवराम कुरकुटे 14', 'shares': 1},
    {'srNo': 296, 'name': 'बाजीराव देवराम कुरकुटे 15', 'shares': 1},
    {'srNo': 297, 'name': 'बाजीराव देवराम कुरकुटे 16', 'shares': 1},
    {'srNo': 298, 'name': 'बाजीराव देवराम कुरकुटे 17', 'shares': 1},
    {'srNo': 299, 'name': 'बाजीराव देवराम कुरकुटे 18', 'shares': 1},
    {'srNo': 300, 'name': 'बाजीराव देवराम कुरकुटे 19', 'shares': 1},
    {'srNo': 301, 'name': 'बाजीराव देवराम कुरकुटे 20', 'shares': 1},
    {'srNo': 302, 'name': 'साहिल बबन शेळके 1', 'shares': 1},
    {'srNo': 303, 'name': 'साहिल बबन शेळके 2', 'shares': 1},
    {'srNo': 304, 'name': 'साहिल बबन शेळके 3', 'shares': 1},
    {'srNo': 305, 'name': 'साहिल बबन शेळके 4', 'shares': 1},
    {'srNo': 306, 'name': 'साहिल बबन शेळके 5', 'shares': 1},
    {'srNo': 307, 'name': 'साहिल बबन शेळके 6', 'shares': 1},
    {'srNo': 308, 'name': 'साहिल बबन शेळके 7', 'shares': 1},
    {'srNo': 309, 'name': 'साहिल बबन शेळके 8', 'shares': 1},
    {'srNo': 310, 'name': 'साहिल बबन शेळके 9', 'shares': 1},
    {'srNo': 311, 'name': 'साहिल बबन शेळके 10', 'shares': 1},
    {'srNo': 312, 'name': 'साहिल बबन शेळके 11', 'shares': 1},
    {'srNo': 313, 'name': 'साहिल बबन शेळके 12', 'shares': 1},
    {'srNo': 314, 'name': 'साहिल बबन शेळके 13', 'shares': 1},
    {'srNo': 315, 'name': 'साहिल बबन शेळके 14', 'shares': 1},
    {'srNo': 316, 'name': 'साहिल बबन शेळके 15', 'shares': 1},
    {'srNo': 317, 'name': 'साहिल बबन शेळके 16', 'shares': 1},
    {'srNo': 318, 'name': 'साहिल बबन शेळके 17', 'shares': 1},
    {'srNo': 319, 'name': 'साहिल बबन शेळके 18', 'shares': 1},
    {'srNo': 320, 'name': 'साहिल बबन शेळके 19', 'shares': 1},
    {'srNo': 321, 'name': 'आकाश चंद्रकांत गुंजाळ 1', 'shares': 1},
    {'srNo': 322, 'name': 'आकाश चंद्रकांत गुंजाळ 2', 'shares': 1},
    {'srNo': 323, 'name': 'आकाश चंद्रकांत गुंजाळ 3', 'shares': 1},
    {'srNo': 324, 'name': 'आकाश चंद्रकांत गुंजाळ 4', 'shares': 1},
    {'srNo': 325, 'name': 'आकाश चंद्रकांत गुंजाळ 5', 'shares': 1},
    {'srNo': 326, 'name': 'आकाश चंद्रकांत गुंजाळ 6', 'shares': 1},
    {'srNo': 327, 'name': 'आकाश चंद्रकांत गुंजाळ 7', 'shares': 1},
    {'srNo': 328, 'name': 'आकाश चंद्रकांत गुंजाळ 8', 'shares': 1},
    {'srNo': 329, 'name': 'आकाश चंद्रकांत गुंजाळ 9', 'shares': 1},
    {'srNo': 330, 'name': 'आकाश चंद्रकांत गुंजाळ 10', 'shares': 1},
    {'srNo': 331, 'name': 'दिपक बाबुराव राहाणे 1', 'shares': 1},
    {'srNo': 332, 'name': 'दिपक बाबुराव राहाणे 2', 'shares': 1},
    {'srNo': 333, 'name': 'दिपक बाबुराव राहाणे 3', 'shares': 1},
    {'srNo': 334, 'name': 'दिपक बाबुराव राहाणे 4', 'shares': 1},
    {'srNo': 335, 'name': 'दिपक बाबुराव राहाणे 5', 'shares': 1},
    {'srNo': 336, 'name': 'दिपक बाबुराव राहाणे 6', 'shares': 1},
    {'srNo': 337, 'name': 'दिपक बाबुराव राहाणे 7', 'shares': 1},
    {'srNo': 338, 'name': 'दिपक बाबुराव राहाणे 8', 'shares': 1},
    {'srNo': 339, 'name': 'दिपक बाबुराव राहाणे 9', 'shares': 1},
    {'srNo': 340, 'name': 'दिपक बाबुराव राहाणे 10', 'shares': 1},
    {'srNo': 341, 'name': 'आशा प्रकाश राहाणे 1', 'shares': 1},
    {'srNo': 342, 'name': 'आशा प्रकाश राहाणे 2', 'shares': 1},
    {'srNo': 343, 'name': 'आशा प्रकाश राहाणे 3', 'shares': 1},
    {'srNo': 344, 'name': 'आशा प्रकाश राहाणे 4', 'shares': 1},
    {'srNo': 345, 'name': 'आशा प्रकाश राहाणे 5', 'shares': 1},
    {'srNo': 346, 'name': 'ओम मोरे (बांबुवाले) 1', 'shares': 1},
    {'srNo': 347, 'name': 'ओम मोरे (बांबुवाले) 2', 'shares': 1},
    {'srNo': 348, 'name': 'ओम मोरे (बांबुवाले) 3', 'shares': 1},
    {'srNo': 349, 'name': 'ओम मोरे (बांबुवाले) 4', 'shares': 1},
    {'srNo': 350, 'name': 'ओम मोरे (बांबुवाले) 5', 'shares': 1},
    {'srNo': 351, 'name': 'सावकार तान्हाजी आहेर', 'shares': 1},
    {'srNo': 352, 'name': 'अनिकेत सुरज घुले 1', 'shares': 1},
    {'srNo': 353, 'name': 'अनिकेत सुरज घुले 2', 'shares': 1},
    {'srNo': 354, 'name': 'अनिकेत सुरज घुले 3', 'shares': 1},
    {'srNo': 355, 'name': 'अनिकेत सुरज घुले 4', 'shares': 1},
    {'srNo': 356, 'name': 'अनिकेत सुरज घुले 5', 'shares': 1},
    {'srNo': 357, 'name': 'अनिकेत सुरज घुले 6', 'shares': 1},
    {'srNo': 358, 'name': 'अनिकेत सुरज घुले 7', 'shares': 1},
    {'srNo': 359, 'name': 'अनिकेत सुरज घुले 8', 'shares': 1},
    {'srNo': 360, 'name': 'अनिकेत सुरज घुले 9', 'shares': 1},
    {'srNo': 361, 'name': 'अनिकेत सुरज घुले 10', 'shares': 1},
    {'srNo': 362, 'name': 'दिनेश शांताराम भालेराव', 'shares': 1},
    {'srNo': 363, 'name': 'ओवी दिनेश भालेराव', 'shares': 1},
  ];

  static Future<void> importExtractedMembers(
      GroupRepository repository,
      ) async {
    await ensureAllMasterMembersSeeded(repository);
  }

  /// Ensures that all 363 master member records exist in the database.
  /// If any member is missing (e.g. from an incomplete previous import),
  /// it seeds only the missing members.
  /// Also cleans up any stale unexpanded records and normalizes all seeded members to have exactly 1 share (₹1,000 monthly).
  static Future<void> ensureAllMasterMembersSeeded(
    GroupRepository repository, {
    String groupId = groupId,
  }) async {
    final membersList = await repository.getMembers(groupId, activeOnly: false);
    final existingMemberMap = <String, Member>{};
    for (final m in membersList) {
      existingMemberMap[m.id] = m;
    }

    final validMasterIds = masterDataset.map((d) => 'M_${d['srNo']}').toSet();

    // 1. Delete any stale unexpanded / legacy member documents in Firestore that have shares > 1
    for (final m in membersList) {
      if (!validMasterIds.contains(m.id) && m.shares > 1) {
        await repository.deleteMember(groupId, m.id);
      }
    }

    final missingMembers = masterDataset
        .where((data) => !existingMemberMap.containsKey('M_${data['srNo']}'))
        .toList();

    final now = DateTime.now();
    for (final data in missingMembers) {
      final member = Member(
        id: 'M_${data['srNo']}',
        groupId: groupId,
        name: data['name'] as String,
        phone: '',
        joinDate: DateTime(2026, 1, 1),
        shares: 1,
        monthlyContributionPerShare: defaultPerShareHafta,
        monthlyContribution: defaultPerShareHafta,
        status: MemberStatus.active,
        createdAt: now,
        updatedAt: now,
      );

      await repository.addMember(member);
    }

    // 2. Normalize all 363 master member records (name with suffix, shares = 1, monthlyContribution = 1000.0)
    for (final data in masterDataset) {
      final memberId = 'M_${data['srNo']}';
      final expectedName = data['name'] as String;
      final existing = existingMemberMap[memberId];
      if (existing != null &&
          (existing.shares != 1 ||
              existing.name != expectedName ||
              existing.monthlyContribution != defaultPerShareHafta ||
              existing.monthlyContributionPerShare != defaultPerShareHafta)) {
        final corrected = existing.copyWith(
          name: expectedName,
          shares: 1,
          monthlyContributionPerShare: defaultPerShareHafta,
          monthlyContribution: defaultPerShareHafta,
          updatedAt: now,
        );
        await repository.updateMember(corrected);
      }
    }
  }
}
