org.gradle.jvmargs=-Xmx4096M -XX:MaxMetaspaceSize=1024m -XX:+UseParallelGC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true

android.useAndroidX=true
android.enableJetifier=false
kotlin.incremental=false
kotlin.incremental.useClasspathSnapshot=false
android.builtInKotlin=false
android.newDsl=false

# Fix for AndroidLocationsBuildService issue
systemProp.user.home=D:/StudioProjects/Bachat-Gat-App/.user_home
gradle.user.home=D:/StudioProjects/Bachat-Gat-App/.gradle_home
systemProp.android.user.home=D:/StudioProjects/Bachat-Gat-App/.android_home
